### ISSUE TITLE
Combined report fails to incorporate all data in ensemble view

### ISSUE THREAD

**Issue by ivanerill** [ErillLab/collectf#44]
When searching with a particular combination of TF, species and techniques, not all data that appears in http://www.collectf.org/browse/search/ after clicking the _Search_ button gets incorporated in the http://www.collectf.org/browse/view_reports_by_id_list page when clicking _Combined report_.

For instance, selecting LexA,  _Mycobacteriaceae_ and _Select all_ - _Binding_ methods yields results for three species: _Mycobacterium leprae, Mycobacterium smegmatis and Mycobacterium tuberculosis_, which can be accessed through the respective _view_ buttons, but only two species (_Mycobacterium leprae and Mycobacterium tuberculosis_) appear in the _Split view_ of the _Combined report_.

**Comment by sefakilic** [comment]
Fixed in d16857a1557408cb794425bb12ff2f47c6c25681
