### ISSUE TITLE
add search by TF name, species name

### ISSUE THREAD

**Issue by ivanerill** [ErillLab/collectf#45]
It would be interesting to add a simple search capability that would allow:
* Entering a TF name (or part thereof), return the TF(s) matching the name and, expanding, the TF instances / species for that TF(s) in the DB, linking to the uniprot-based report
* Entering a species name (or part thereof), return the (multiple) species matching the name and, expanding, the TF instances / species for that species in the DB, linking to the uniprot-based report

**Comment by sefakilic** [comment]
We have it now.
