### ISSUE TITLE
Move navigation column on homepage to the right.

### ISSUE THREAD

**Issue by Dinara** [ErillLab/collectf#7]
Sefa and I talked about using Github issues option for CollecTF. 
So here is my first shot at using it. I switched the layout of the boxes in <i>homepage_base.html</i> and replaced <b>{% block right-frame %}</b> tag with <b>{% block left-frame %}</b> in each page extending homepage_base.html. 
I think it is slightly more aesthetically pleasing to see the main content div on the left and nav column on the right. 
Let me know what you think. 
![issue 1](https://cloud.githubusercontent.com/assets/4400944/6713732/b30a5e20-cd6a-11e4-8f6f-903329fca733.png)
![issue1_1](https://cloud.githubusercontent.com/assets/4400944/6714044/92543a00-cd6c-11e4-8d11-e5e1091c2111.png)

**Comment by sefakilic** [comment]
Dinara, 

I think this is a small change but it would improve the interface a lot! Thanks. Let's talk to Dr. Erill.

**Comment by ivanerill** [comment]
I am kind of used to seeing the menus on the left, but I agree it is
probably more aesthetically pleasing on the right.

**Comment by sefakilic** [comment]
On a second thought, this may not be a good idea: when the window is narrow, the navigation goes to the bottom of the page. It stays at the top only if it is on the left side.
